model:
  g: 9.81

  cart_mass: 0.390

  pendulum_mass: 0.614
  pendulum_height: 0.154

  wheel_radius: 0.035
  wheel_base: 0.183

ctrl:
  theta_k: 15.0
  theta_dot_k: 2.0
  x_k: 0.0 #0.5
  x_dot_k: -2.5
  omega_k: -0.05
  x_dot_abs_max: 2.0

joy:
  k_j_omega: -5.0
  k_j_x_dot: -1.0
