model:
  g: 9.81

  m_c: 0.390

  m_p: 0.614
  h_p: 0.154

  wheel_radius: 0.035
  wheel_base: 0.183

ctrl:
  theta_k: -3.0
  theta_theta_dot_k: 0.8
  theta_dot_k: 1.5
  x_k: 0.1
  x_dot_k: -2.0
  x_ddot_max: 5.0
  x_dot_abs_max: 5.0
  omega_k: -0.05

joy:
  k_j_omega: -5.0
  k_j_x_dot: -3.0
